---
apiVersion: v1
kind: Namespace
metadata:
  name: red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker
  namespace: red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
      - name: attacker
        image: nicolaka/netshoot
        command: ["sleep","3600"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable
  template:
    metadata:
      labels:
        app: vulnerable
    spec:
      containers:
      - name: vulnerable
        image: hashicorp/http-echo
        args: ["-text=vulnerable"]
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-svc
  namespace: app
spec:
  selector:
    app: vulnerable
  ports:
  - port: 8081
    targetPort: 8081