# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

####################################################################
##							
## Para rodar capturando os outputs:		
##					
## vagrant up | Tee-Object -FilePath "vagrant_output.log" -Append
##						
####################################################################

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.boot_timeout = 900

# ===================================================================
#  VM Docker TOOLS - 10.10.10.101
# ===================================================================
  config.vm.define "Docker-Tools" do |node|
    node.vm.box = "debian/bookworm64"
    node.vm.hostname = "Docker-Tools"
		
    node.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = 6144
      vb.cpus = 2
      vb.name = "Docker-Tools"
	  vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
	  vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
   end
   
   # Provisionamento específico para o docker tools
  config.vm.provision "shell", inline: <<-SHELL
    
	# Baixa o script de provisionamento principal do GitHub
    wget -O /tmp/provisionamento_docker_tools.sh https://raw.githubusercontent.com/EstudanteDeCyber/laboratorios/main//scripts/provisionamento_docker_tools.sh
    chmod +x /tmp/provisionamento_docker_tools.sh
    
    # Executa o script
    bash /tmp/provisionamento_docker_tools.sh
	
  SHELL
 end
end
